version: '3.9'

services:
  beanstalkd:
    image: bodsch/docker-beanstalkd
    ports:
      - "11300:11300"
    volumes:
      - ./beanstalkd_data:/data

  ruby_app:
    container_name: ruby_app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./put_message_into_beanstalkd.rb:/scripts/put_message_into_beanstalkd.rb

  redis_rdb:
    image: redis:latest
    command: ["redis-server", "--save", "1", "1", "--appendonly", "no"]
    volumes:
      - ./redis_rdb_data:/data
      - ./redis_test.rb:/scripts/redis_test.rb
      - ./pub_sub_redis_test.rb:/scripts/pub_sub_redis_test.rb
    ports:
      - "6379:6379"

  redis_rdb_default:
    image: redis:latest
    command: ["redis-server", "--save", "900", "1", "--appendonly", "no"]
    volumes:
      - ./redis_rdb_default_data:/data
    ports:
      - "6380:6379"

  redis_aof:
    image: redis:latest
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - ./redis_aof_data:/data
    ports:
      - "6381:6379"

  redis_no_persistence:
    image: redis:latest
    command: ["redis-server", "--save"]
    ports:
      - "6382:6379"

volumes:
  beanstalkd_data:
  redis_rdb_data:
  redis_rdb_default_data:
  redis_aof_data: